fragment CustomerFields on Customer {
  id
  email
  firstName
  lastName
}

fragment OrderItemFields on OrderItem {
  id
  name
  price
  qty
  productId
  details
  createdAt
}

fragment RefundFields on Refund {
  id
  paymentId
  status
  amount
  orderCurrencyAmount
  merchantId
  externalId
  reason
  createdAt
  updatedAt
}

fragment PaymentFields on Payment {
  id
  orderId
  status
  amount
  currency
  orderCurrencyAmount
  refundedAmount
  paymentMethodId
  externalId
  merchantId
  isManual
  ip
  redirectUrl
  error
  errorMessage
  rejectReason
  createdAt
  updatedAt
}

fragment PaymentWithRefunds on Payment {
  ...PaymentFields
  refunds {
    ...RefundFields
  }
}

fragment OrderFields on Order {
  id
  status
  merchantId
  title
  price
  currency
  currentPrice
  paidAmount
  refundedAmount
  remainingAmount
  customerId
  projectId
  subscriptionId
  returnUrl
  webhookUrl
  metadata
  ip
  deadlineDate
  createdAt
  updatedAt
}

fragment OrderDetail on Order {
  ...OrderFields
  customer {
    ...CustomerFields
  }
  items {
    ...OrderItemFields
  }
  payments {
    ...PaymentWithRefunds
  }
}

fragment ProductFields on Product {
  id
  externalId
  name
  price
  currency
  imageUrl
  subscriptionInterval
  customInterval
  additionalParameters
  projectId
  deletedAt
  createdAt
}

fragment SubscriptionItemPauseFields on SubscriptionItemPause {
  id
  subscriptionItemId
  startsAt
  endsAt
  createdAt
}

fragment SubscriptionItemPriceFields on SubscriptionItemPrice {
  id
  subscriptionItemId
  price
  qty
  startsAt
  createdAt
}

fragment SubscriptionItemFields on SubscriptionItem {
  id
  subscriptionId
  externalId
  externalProductId
  productId
  name
  imageUrl
  price
  qty
  details
  startsAt
  endsAt
  isActive
  isPaused
  createdAt
  updatedAt
}

fragment SubscriptionItemDetail on SubscriptionItem {
  ...SubscriptionItemFields
  product {
    ...ProductFields
  }
  prices {
    ...SubscriptionItemPriceFields
  }
}

fragment SubscriptionFields on Subscription {
  id
  customerId
  title
  currency
  interval
  customInterval
  paymentInAdvance
  paymentMethod
  paymentTokenId
  firstBillingDate
  currentBillingDate
  lastBillingDate
  isActive
  webhookUrl
  createdAt
  updatedAt
}

fragment VoucherFields on Voucher {
  id
  code
  groupId
  generationId
  balance
  activeBalance
  startBalance
  isArchived
  projectId
  createdAt
  updatedAt
}

fragment VoucherGroupFields on VoucherGroup {
  id
  name
  currency
  codeLength
  startsAt
  endsAt
  isActive
  balanceSum
  startBalanceSum
  createdAt
  updatedAt
}
